ALTER TABLE BOOK_AUTHOR DROP FOREIGN KEY FK_BOOK_AUTHOR_Book_ID
ALTER TABLE BOOK_AUTHOR DROP FOREIGN KEY FK_BOOK_AUTHOR_authors_ID
DROP TABLE BOOK
DROP TABLE CD
DROP TABLE AUTHOR
DROP TABLE BOOK_AUTHOR
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
